version: "3.9"
services:
  flask_sender:
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_DEBUG: "true"
    command: flask --app redis_experiments/sender_service/app.py run
    depends_on:
      - redis

  flask_receiver:
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "8001:5000"
    volumes:
      - .:/src
    environment:
      FLASK_DEBUG: "true"
    command: flask --app redis_experiments/receiver_service/app.py run
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
