version: "3.9"
services:
  flask_sender:
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./redis_experiments:/app
    environment:
      FLASK_DEBUG: "true"
    command: flask --app sender_service/app.py run
    depends_on:
      - redis

  flask_receiver:
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "8001:5000"
    volumes:
      - ./redis_experiments:/app
    environment:
      FLASK_DEBUG: "true"
    command: flask --app receiver_service/app.py run
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"  # Expose redis on the local host, so that we can access it more easily
