version: "3.9"
services:
  flask_sender:
    build:
      dockerfile: redis_experiments/sender_service/Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_DEBUG: "true"

  flask_receiver:
    build:
      dockerfile: redis_experiments/receiver_service/Dockerfile
    ports:
      - "8001:5000"
    volumes:
      - .:/src
    environment:
      FLASK_DEBUG: "true"

  redis:
    image: "redis:alpine"
